sudo: required
services:
  - docker
language: go
go:
  - "1.6"
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - dep ensure
  - docker-compose up -d
jobs:
  include:
    - stage: code style
    - script: golint -set_exit_status && go vet
    - stage: test
    - script: make migrate && make test && make test-integration && make build
stages:
  - code style
  - test
