version: '3'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - 1000:27017
  db-gui:
    image: mrvautin/adminmongo
    ports:
      - 8082:1234
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  redis-gui:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
