// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fossapps/starter (interfaces: RequestHelper)

// Package mocks is a generated GoMock package.
package mocks

import (
	adapters "github.com/fossapps/starter/adapters"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockRequestHelper is a mock of RequestHelper interface
type MockRequestHelper struct {
	ctrl     *gomock.Controller
	recorder *MockRequestHelperMockRecorder
}

// MockRequestHelperMockRecorder is the mock recorder for MockRequestHelper
type MockRequestHelperMockRecorder struct {
	mock *MockRequestHelper
}

// NewMockRequestHelper creates a new mock instance
func NewMockRequestHelper(ctrl *gomock.Controller) *MockRequestHelper {
	mock := &MockRequestHelper{ctrl: ctrl}
	mock.recorder = &MockRequestHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRequestHelper) EXPECT() *MockRequestHelperMockRecorder {
	return m.recorder
}

// GetIPAddress mocks base method
func (m *MockRequestHelper) GetIPAddress(arg0 *http.Request) string {
	ret := m.ctrl.Call(m, "GetIPAddress", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIPAddress indicates an expected call of GetIPAddress
func (mr *MockRequestHelperMockRecorder) GetIPAddress(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPAddress", reflect.TypeOf((*MockRequestHelper)(nil).GetIPAddress), arg0)
}

// GetJwtData mocks base method
func (m *MockRequestHelper) GetJwtData(arg0 *http.Request) (*adapters.Claims, error) {
	ret := m.ctrl.Call(m, "GetJwtData", arg0)
	ret0, _ := ret[0].(*adapters.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJwtData indicates an expected call of GetJwtData
func (mr *MockRequestHelperMockRecorder) GetJwtData(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJwtData", reflect.TypeOf((*MockRequestHelper)(nil).GetJwtData), arg0)
}
